# Site settings
title: County Chamber Collective
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "countychambercollective.ca" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
